scheme: Gemini
darkmode: true
menu_settings:
  icons: true
menu:
  home: / || fa fa-home
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
sidebar: left
